export const ADD_PROJECT_FAILURE = "ADD_PROJECT_FAILURE";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_STARTED = "ADD_PROJECT_STARTED";

export const GET_ALL_PROJECTS_FAILURE = "GET_ALL_PROJECT_FAILURE";
export const GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECT_SUCCESS";
export const GET_ALL_PROJECTS_STARTED = "GET_ALL_PROJECT_STARTED";

export const DELETE_PROJECTS_FAILURE = "DELETE_PROJECT_FAILURE";
export const DELETE_PROJECTS_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECTS_STARTED = "DELETE_PROJECT_STARTED";
